### ISSUE TITLE
Song Request

### ISSUE THREAD

**Issue by utkudarilmaz** [oz9un/Developers-Playlist#20]
Jay-Jay Johanson - Heard Somebody Whistle

**Comment by utkudarilmaz** [comment]
It's added wrong song @oz9un .
I suppose dash on the artist's name is broking something.

**Comment by oz9un** [comment]
Thanks for the feedback @utkudarilmaz ! Yes, I am aware of this issue. I used to split with semicolon, but dash seems more user-friendly. 

Before fixing that issue with re-writing the splitting process, I should add a warning to README. 

It'll probably work flawless if we omit the dash in the artist's name though.

Thanks again!
